### ISSUE TITLE
Crash on my manjaro

### ISSUE THREAD

**Issue by Esclapion** [MartijnBraam/setres#1]
```
[pat@lq64 ~]$ setres 1920 1080
Traceback (most recent call last):
  File "/usr/bin/setres", line 11, in <module>
    load_entry_point('setres==0.2', 'console_scripts', 'setres')()
  File "/usr/lib/python3.5/site-packages/setres/__main__.py", line 134, in main
    if not active_port.has_mode(args.width, args.height, args.rate, args.interlaced):
AttributeError: 'NoneType' object has no attribute 'has_mode'
```

**Comment by MartijnBraam** [comment]
What's the output if you execute the `xrandr` command without parameters?

**Comment by Esclapion** [comment]
``` bash
[pat@lq64 ~]$ xrandr
Screen 0: minimum 8 x 8, current 1680 x 1050, maximum 16384 x 16384
DVI-I-0 disconnected primary (normal left inverted right x axis y axis)
DVI-I-1 connected 1680x1050+0+0 (normal left inverted right x axis y axis) 478mm x 300mm
   1680x1050     59.95*+
   1440x900      74.98    59.89  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94  
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
DVI-D-0 disconnected (normal left inverted right x axis y axis)
```

(edit)
same problem for setres 1280 1024

**Comment by MartijnBraam** [comment]
None of my ports had dashes in the name. Can you try the newest version (0.3)

**Comment by Esclapion** [comment]
```
[pat@lq64 ~]$ setres  1280 1024
This mode does not exist for port DVI-I-0
Adding new mode to DVI-I-0
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  18 (RRAddOutputMode)
  Serial number of failed request:  39
  Current serial number in output stream:  40
Traceback (most recent call last):
  File "/usr/bin/setres", line 11, in <module>
    load_entry_point('setres==0.3', 'console_scripts', 'setres')()
  File "/usr/lib/python3.5/site-packages/setres/__main__.py", line 140, in main
    active_port.add_mode(args.width, args.height, args.rate)
  File "/usr/lib/python3.5/site-packages/setres/__main__.py", line 77, in add_mode

```

maybe i must install something, i have only xrandr.

**Comment by MartijnBraam** [comment]
Can you try `setres --port DVI-I-1 1280 1024`
Your xrandr output lists DVI-I-1 as the only connected port but DVI-I-0 is the primary monitor.

**Comment by Esclapion** [comment]
It works very well. But  how can I go back now ?

```
[pat@lq64 ~]$ setres --port DVI-I-1 1680  1050
Traceback (most recent call last):
  File "/usr/bin/setres", line 11, in <module>
    load_entry_point('setres==0.3', 'console_scripts', 'setres')()
  File "/usr/lib/python3.5/site-packages/setres/__main__.py", line 111, in main
    ports = get_ports()
  File "/usr/lib/python3.5/site-packages/setres/__main__.py", line 102, in get_ports
    port = Port(*port)
  File "/usr/lib/python3.5/site-packages/setres/__main__.py", line 27, in __init__
    self._parse_resolutions(resolutions)
  File "/usr/lib/python3.5/site-packages/setres/__main__.py", line 53, in _parse_resolutions
    rate = float(rate)
ValueError: could not convert string to float:
```

(edit)

```
[pat@lq64 ~]$ xrandr
Screen 0: minimum 8 x 8, current 1280 x 1024, maximum 16384 x 16384
DVI-I-0 disconnected primary (normal left inverted right x axis y axis)
DVI-I-1 connected 1280x1024+0+0 (normal left inverted right x axis y axis) 480mm x 300mm
   1680x1050     59.95 +
   1440x900      74.98    59.89  
   1280x1024     75.02*   60.02  
   1280x960      60.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94  
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
DVI-D-0 disconnected (normal left inverted right x axis y axis)
  1280x1024_60.00 (0x274) 109.000MHz -HSync +VSync
        h: width  1280 start 1368 end 1496 total 1712 skew    0 clock  63.67KHz
        v: height 1024 start 1027 end 1034 total 1063           clock  59.89Hz
```

**Comment by MartijnBraam** [comment]
The argument parser doesn't seem to like the two spaces between the width and height in your command. Looks like a bug in the python ArgumentParser module.

**Comment by Esclapion** [comment]
This name has been automatically generated, I changed manually nothing, so it will be a "normal" case.

**Comment by MartijnBraam** [comment]
I mean in your command:

``` bash
$ setres --port DVI-I-1 1680  1050
                             ^
```

Edit: Oh I see what you mean, there is also a bug in the resolution list parsing.

**Comment by Esclapion** [comment]
With one blank, the same. What can I use as separator ?

(edit)

```
[pat@lq64 ~]$ setres --port "DVI-I-1" 1680 1050
Traceback (most recent call last):
  File "/usr/bin/setres", line 11, in <module>
    load_entry_point('setres==0.3', 'console_scripts', 'setres')()
  File "/usr/lib/python3.5/site-packages/setres/__main__.py", line 111, in main
    ports = get_ports()
  File "/usr/lib/python3.5/site-packages/setres/__main__.py", line 102, in get_ports
    port = Port(*port)
  File "/usr/lib/python3.5/site-packages/setres/__main__.py", line 27, in __init__
    self._parse_resolutions(resolutions)
  File "/usr/lib/python3.5/site-packages/setres/__main__.py", line 53, in _parse_resolutions
    rate = float(rate)
ValueError: could not convert string to float: 

```

**Comment by MartijnBraam** [comment]
Can you try version 0.4?

**Comment by Esclapion** [comment]
Works ! :-)

Thanks ;)
